# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
  aws-cli: circleci/aws-cli@4.0.0
# Orchestrate or schedule a set of jobs

# Define the jobs we want to run for this project
jobs:
  print_greetings:  # Choose any name, such as `build`
    # The primary container, where your job's commands will run
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - print_greetings
