---
- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Install dependencies (Node.js and NPM)
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: Install PM2
  become: true
  npm:
    name: pm2
    global: yes

- name: Create web directory
  become: true
  file:
    path: ~/web
    state: directory

- name: Copy index.js test page
  become: true
  copy:
    src: files/index.js
    dest: ~/web/index.js

- name: Start web server with PM2
  become: true
  shell: pm2 start ~/web/index.js -f
